/**:                 # /** This will put all the parameters in every node
  ros__parameters:
    
    static_obs_list: "[[0.0, 0.0, 0.25],]" #format [x,y,prohibited_rad]

    robot_ids: ['0']



# i = 0

# for char in string:
#   if char == '[':

#     if i:
#       temp = np.array([])

#     i += 1

#   elif char ==']':
#     i -= 1
#     if i:
#       temp = np.expand_dims(temp, 0)
#       print(temp.shape)
#       print(converted_arr.shape)
#       converted_arr = np.append(converted_arr, temp, axis = 0)

    
    

#   try:
#     temp = np.append(temp, float(char))
    

#   except ValueError:
#     continue

#   except IndexError:
#     print("Invalid input")
#     #raise ros2 exception

# converted_arr = converted_arr[1:][:]


  

